### ISSUE TITLE
Andor's crop mode crashes python

### ISSUE THREAD

**Issue by eoinell** [nanophotonics/nplab#107]
clicking the 'crop' mode on the Andor gui crashes python

**Comment by eoinell** [comment]
the set_image function appears to be deprecated
```
            self.Andor.set_image(1, maxy, maxx, current_binning, current_binning)
        else:
            self.Andor.set_camera_parameter('IsolatedCropMode', 0, maxy, maxx, current_binning, current_binning)
            self.Andor.set_image()

```
what did it do?

**Comment by YagoDel** [comment]
Have a go now

**Comment by eoinell** [comment]
The crop mode now works thanks! The roi mode however crashes:
![image](https://user-images.githubusercontent.com/43847943/72607789-3555c300-3919-11ea-84df-c1bedf2c0d45.png)
I'm not clear on what the difference between the two modes should even be tbh

**Comment by YagoDel** [comment]
Did it crash before or after you made this commit 1184f81d9e3f6a6228c6dd0edd61c2e479caacbd? I ask because self.detector

Cropping changes the effective size of the detector (changing self.detector_shape as well). I think it's intended for when part of the CCD is not in the optical path. There is a slight difference in how the electronics readout the CCD charge (changing things like speed and noise level). And in principle you could crop the CCD, and then use a ROI on top of that, but I haven't figured out how to make a GUI for that, so it's not implemented.
For most purposes, the only difference is that one of the cropping vertices is always the top-left, whilst ROI can happen in any rectangle

**Comment by eoinell** [comment]
After. 

But the crop checkbox caused python to crash before I did this because the `detector_shape` attribute was NoneType.

**Comment by YagoDel** [comment]
Weird. I'll have a look Monday (obvs not in the lab anymore today). It'd be helpful if you check if it works before that commit

**Comment by eoinell** [comment]
Yeah it was that commit that was breaking it. I just changed detector shape to 1 and now neither errors appear :)
