### ISSUE TITLE
Data browser window only with 'block=True'

### ISSUE THREAD

**Issue by jm806** [nanophotonics/nplab#28]
The data browser window disappears directly when 'block=False'. There is a reference of the GUI though. 
Using 'block=True' keeps the GUI alive

**Comment by rwb27** [comment]
I can't reproduce this on my mac.  Odd.  Need to try on Windows...

**Comment by rwb27** [comment]
I've reproduced this on Windows using the current master branch.  The problem goes away if I put the line `app = get_qt_app()` before popping up the GUI, I guess the problem is you need to hold on to the Qt application in order to avoid it getting garbage collected.  Quite why this has changed I can't understand!  Perhaps something updated in PyQt?  Either way, I'll make the code hold on to a reference to the Qt application, and hopefully that will fix things.

**Comment by rwb27** [comment]
Actually, 4270372 fixed it.  I screwed up the global variable thing in the previous commit.
